// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const channelsTable = {
  name: "channels",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "channel",
} as const;
const messagesTable = {
  name: "messages",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
    senderID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "sender_id",
    },
    channelID: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
      serverName: "channel_id",
    },
    body: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
  },
  primaryKey: ["id"],
  serverName: "message",
} as const;
const usersTable = {
  name: "users",
  columns: {
    id: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    email: {
      type: "string",
      optional: false,
      customType: null as unknown as string,
    },
    emailVerified: {
      type: "boolean",
      optional: true,
      customType: null as unknown as boolean,
      serverName: "email_verified",
    },
    image: {
      type: "string",
      optional: true,
      customType: null as unknown as string,
    },
    createdAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "created_at",
    },
    updatedAt: {
      type: "number",
      optional: true,
      customType: null as unknown as number,
      serverName: "updated_at",
    },
  },
  primaryKey: ["id"],
  serverName: "user",
} as const;
const channelsRelationships = {
  messages: [
    {
      sourceField: ["id"],
      destField: ["channelID"],
      destSchema: "messages",
      cardinality: "many",
    },
  ],
} as const;
const messagesRelationships = {
  sender: [
    {
      sourceField: ["senderID"],
      destField: ["id"],
      destSchema: "users",
      cardinality: "one",
    },
  ],
  channel: [
    {
      sourceField: ["channelID"],
      destField: ["id"],
      destSchema: "channels",
      cardinality: "one",
    },
  ],
} as const;
const usersRelationships = {
  messages: [
    {
      sourceField: ["id"],
      destField: ["senderID"],
      destSchema: "messages",
      cardinality: "many",
    },
  ],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    channels: channelsTable,
    messages: messagesTable,
    users: usersTable,
  },
  relationships: {
    channels: channelsRelationships,
    messages: messagesRelationships,
    users: usersRelationships,
  },
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "channels" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["channels"] instead from "@rocicorp/zero".
 */
export type Channel = Row["channels"];
/**
 * Represents a row from the "messages" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["messages"] instead from "@rocicorp/zero".
 */
export type Message = Row["messages"];
/**
 * Represents a row from the "users" table.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use Row["users"] instead from "@rocicorp/zero".
 */
export type User = Row["users"];

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 *
 * @deprecated Use `zql` instead.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
